version: '3'
services:
  mysql-db:
    image: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
    volumes:
      - "./trainingDB.sql:/docker-entrypoint-initdb.d/init.sql"
